---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-filepath
          - ./license_header.txt

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
